// <auto-generated />
using System;
using DKH.CustomerService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DKH.CustomerService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260216010139_AddProviderTypeRenameUserId")]
    partial class AddProviderTypeRenameUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.CustomerAddress.CustomerAddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apartment")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Building")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Street")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerId", "IsDefault")
                        .HasFilter("\"IsDefault\" = true");

                    b.ToTable("customer_addresses", (string)null);
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.CustomerProfile.CustomerProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Telegram")
                        .HasColumnName("provider_type");

                    b.Property<Guid>("StorefrontId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Phone");

                    b.HasIndex("StorefrontId", "UserId")
                        .IsUnique();

                    b.ToTable("customer_profiles", (string)null);
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.WishlistItem.WishlistItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSkuId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerId", "ProductId", "ProductSkuId")
                        .IsUnique();

                    b.ToTable("wishlist_items", (string)null);
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.CustomerAddress.CustomerAddressEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.CustomerProfile.CustomerProfileEntity", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.CustomerProfile.CustomerProfileEntity", b =>
                {
                    b.OwnsOne("DKH.CustomerService.Domain.ValueObjects.AccountStatus", "AccountStatus", b1 =>
                        {
                            b1.Property<Guid>("CustomerProfileEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BlockReason")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("block_reason");

                            b1.Property<DateTime?>("BlockedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("blocked_at");

                            b1.Property<string>("BlockedBy")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("blocked_by");

                            b1.Property<DateTime?>("LastActivityAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_activity_at");

                            b1.Property<DateTime?>("LastLoginAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_login_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasDefaultValue("Active")
                                .HasColumnName("account_status");

                            b1.Property<DateTime?>("SuspendedUntil")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("suspended_until");

                            b1.Property<int>("TotalOrdersCount")
                                .HasColumnType("integer")
                                .HasColumnName("total_orders_count");

                            b1.Property<decimal>("TotalSpent")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_spent");

                            b1.HasKey("CustomerProfileEntityId");

                            b1.ToTable("customer_profiles");

                            b1.WithOwner()
                                .HasForeignKey("CustomerProfileEntityId");
                        });

                    b.OwnsOne("DKH.CustomerService.Domain.ValueObjects.ContactVerification", "ContactVerification", b1 =>
                        {
                            b1.Property<Guid>("CustomerProfileEntityId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("EmailVerified")
                                .HasColumnType("boolean")
                                .HasColumnName("email_verified");

                            b1.Property<DateTime?>("EmailVerifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("email_verified_at");

                            b1.Property<bool>("PhoneVerified")
                                .HasColumnType("boolean")
                                .HasColumnName("phone_verified");

                            b1.Property<DateTime?>("PhoneVerifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("phone_verified_at");

                            b1.HasKey("CustomerProfileEntityId");

                            b1.ToTable("customer_profiles");

                            b1.WithOwner()
                                .HasForeignKey("CustomerProfileEntityId");
                        });

                    b.OwnsOne("DKH.CustomerService.Domain.ValueObjects.CustomerPreferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("CustomerProfileEntityId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("EmailNotificationsEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("email_notifications_enabled");

                            b1.Property<bool>("OrderStatusUpdates")
                                .HasColumnType("boolean")
                                .HasColumnName("order_status_updates");

                            b1.Property<string>("PreferredCurrency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("preferred_currency");

                            b1.Property<string>("PreferredLanguage")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("preferred_language");

                            b1.Property<bool>("PromotionalOffers")
                                .HasColumnType("boolean")
                                .HasColumnName("promotional_offers");

                            b1.Property<bool>("SmsNotificationsEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("sms_notifications_enabled");

                            b1.Property<bool>("TelegramNotificationsEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("telegram_notifications_enabled");

                            b1.HasKey("CustomerProfileEntityId");

                            b1.ToTable("customer_profiles");

                            b1.WithOwner()
                                .HasForeignKey("CustomerProfileEntityId");
                        });

                    b.Navigation("AccountStatus")
                        .IsRequired();

                    b.Navigation("ContactVerification")
                        .IsRequired();

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.WishlistItem.WishlistItemEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.CustomerProfile.CustomerProfileEntity", null)
                        .WithMany("WishlistItems")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.CustomerProfile.CustomerProfileEntity", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
