// <auto-generated />
using System;
using DKH.CustomerService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DKH.CustomerService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009170132_AddPrivateDatedExperienceJournal")]
    partial class AddPrivateDatedExperienceJournal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DKH.CustomerService.Domain.Authorization.CustomerAccessGrantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrantReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte>("SubjectType")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("SubjectType", "SubjectId", "ResourceType")
                        .HasDatabaseName("ix_customer_access_grants_subject")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("ResourceType", "ResourceId", "SubjectType", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_access_grants_unique")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("customer_access_grants", (string)null);
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.CustomerAccount.CustomerAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentityIssuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("identity_issuer");

                    b.Property<string>("IdentitySubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("identity_subject");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PreferredLocale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("preferred_locale");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<string>("VerifiedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("verified_email");

                    b.HasKey("Id");

                    b.HasIndex("VerifiedEmail")
                        .HasDatabaseName("ix_customer_accounts_verified_email");

                    b.HasIndex("IdentityIssuer", "IdentitySubject")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_accounts_issuer_subject");

                    b.ToTable("customer_accounts", (string)null);
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.CustomerAccount.LinkedCustomerIdentityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_account_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LegacyExternalIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legacy_external_identity_id");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<string>("ProviderAuthority")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("provider_authority");

                    b.Property<string>("ProviderKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider_kind");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_subject");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId")
                        .HasDatabaseName("ix_linked_customer_identities_account");

                    b.HasIndex("LegacyExternalIdentityId")
                        .IsUnique()
                        .HasDatabaseName("ux_linked_customer_identities_legacy")
                        .HasFilter("\"legacy_external_identity_id\" IS NOT NULL");

                    b.HasIndex("ProviderAuthority", "ProviderSubject")
                        .IsUnique()
                        .HasDatabaseName("ux_linked_customer_identities_authority_subject");

                    b.ToTable("linked_customer_identities", (string)null);
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.CustomerAddress.CustomerAddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Apartment")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Building")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Company")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Street")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerId", "IsDefault")
                        .HasFilter("\"IsDefault\" = true");

                    b.ToTable("customer_addresses", (string)null);
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.CustomerProfile.CustomerProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AccountReconciliationAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("account_reconciliation_attempt_count");

                    b.Property<string>("AccountReconciliationReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_reconciliation_reason_code");

                    b.Property<string>("AccountReconciliationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("PendingProof")
                        .HasColumnName("account_reconciliation_status");

                    b.Property<bool>("AllowsWriteToPm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allows_write_to_pm");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_account_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_premium");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("LastAccountReconciliationAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_account_reconciliation_attempt_at");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Telegram")
                        .HasColumnName("provider_type");

                    b.Property<Guid>("StorefrontId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("Email");

                    b.HasIndex("Phone");

                    b.HasIndex("AccountReconciliationStatus", "LastAccountReconciliationAttemptAt");

                    b.HasIndex("StorefrontId", "UserId")
                        .IsUnique();

                    b.ToTable("customer_profiles", (string)null);
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<long>("CurrentRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("current_revision");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("LocalTimeIso")
                        .HasColumnType("text")
                        .HasColumnName("local_time_iso");

                    b.Property<DateOnly>("OccurredDate")
                        .HasColumnType("date")
                        .HasColumnName("occurred_date");

                    b.Property<Guid>("OriginStorefrontId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_storefront_id");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("RetainedTargetLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retained_target_label");

                    b.Property<int?>("SessionScore")
                        .HasColumnType("integer")
                        .HasColumnName("session_score");

                    b.Property<int>("TimePrecision")
                        .HasColumnType("integer")
                        .HasColumnName("time_precision");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<Guid?>("UnknownReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("unknown_reference_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int?>("UtcOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("utc_offset_minutes");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "UnknownReferenceId");

                    b.HasIndex("AccountId", "OccurredDate", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_journal_owner_date_id")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("AccountId", "ProductId", "OccurredDate", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_journal_owner_product_date_id")
                        .HasFilter("is_deleted = false AND product_id IS NOT NULL");

                    b.ToTable("journal_experience_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_journal_entry_ids", "origin_storefront_id <> '00000000-0000-0000-0000-000000000000'::uuid AND (product_id IS NULL OR product_id <> '00000000-0000-0000-0000-000000000000'::uuid) AND (release_id IS NULL OR release_id <> '00000000-0000-0000-0000-000000000000'::uuid)");

                            t.HasCheckConstraint("ck_journal_entry_label", "char_length(retained_target_label) BETWEEN 1 AND 256");

                            t.HasCheckConstraint("ck_journal_entry_revision", "current_revision > 0");

                            t.HasCheckConstraint("ck_journal_entry_score", "session_score IS NULL OR session_score BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_journal_entry_target", "((product_id IS NOT NULL)::int + (unknown_reference_id IS NOT NULL)::int) = 1 AND (release_id IS NULL OR product_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_journal_entry_time", "(time_precision = 1 AND local_time_iso IS NULL AND time_zone IS NULL AND utc_offset_minutes IS NULL) OR (time_precision = 2 AND local_time_iso IS NOT NULL AND utc_offset_minutes IS NOT NULL AND local_time_iso ~ '^([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9][.][0-9]{7}$' AND time_zone IS NOT NULL AND char_length(time_zone) BETWEEN 1 AND 128 AND utc_offset_minutes BETWEEN -1440 AND 1440)");
                        });
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceMutationReceiptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifier_id");

                    b.Property<int>("Operation")
                        .HasColumnType("integer")
                        .HasColumnName("operation");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_hash");

                    b.Property<long>("ResultRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("result_revision");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_journal_receipt_expiry");

                    b.HasIndex("AccountId", "EntryId", "ResultRevision");

                    b.HasIndex("AccountId", "Operation", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_journal_owner_operation_key");

                    b.ToTable("journal_experience_mutation_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_journal_receipt_key", "idempotency_key <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_journal_receipt_shape", "operation IN (1,2,3,4) AND result_revision > 0 AND request_hash ~ '^[0-9a-f]{64}$' AND expires_at_utc = created_at_utc + interval '24 hours'");
                        });
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceProfileSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalSchema")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_schema");

                    b.Property<Guid?>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("RendererCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("renderer_code");

                    b.Property<int>("RendererVersion")
                        .HasColumnType("integer")
                        .HasColumnName("renderer_version");

                    b.Property<string>("SchemaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schema_hash");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("Id");

                    b.HasIndex("SchemaHash")
                        .IsUnique()
                        .HasDatabaseName("ux_journal_profile_schema_hash");

                    b.ToTable("journal_experience_profile_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_journal_profile_binding", "(renderer_code = 'general' AND renderer_version = 1 AND catalog_id IS NULL AND category_id IS NULL) OR (renderer_code <> 'general' AND catalog_id IS NOT NULL AND category_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_journal_profile_schema", "schema_version = 1 AND renderer_version > 0 AND char_length(renderer_code) BETWEEN 1 AND 64 AND schema_hash ~ '^[0-9a-f]{64}$' AND octet_length(canonical_schema) <= 131072 AND jsonb_typeof(canonical_schema::jsonb) = 'object'");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9eb970a-7e55-54f3-9aaa-74e3383ee0de"),
                            CanonicalSchema = "{\"catalogId\":null,\"categoryId\":null,\"definitions\":[],\"rendererCode\":\"general\",\"rendererVersion\":1,\"schemaVersion\":1}",
                            CreationTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RendererCode = "general",
                            RendererVersion = 1,
                            SchemaHash = "f9eb970a7e5524f39aaa74e3383ee0ded5e8f17450a9fc58956ccd0cfe512371",
                            SchemaVersion = 1
                        });
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("CanonicalPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_payload");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsDeletion")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deletion");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_hash");

                    b.Property<Guid>("ProfileSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_snapshot_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("Id");

                    b.HasIndex("ProfileSnapshotId");

                    b.HasIndex("EntryId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ux_journal_entry_revision");

                    b.ToTable("journal_experience_revisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_journal_revision_payload", "revision > 0 AND schema_version = 1 AND payload_hash ~ '^[0-9a-f]{64}$' AND octet_length(canonical_payload) <= 131072 AND jsonb_typeof(canonical_payload::jsonb) = 'object'");
                        });
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceRevisionObservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("boolean")
                        .HasColumnName("boolean_value");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<decimal?>("DecimalValue")
                        .HasColumnType("numeric")
                        .HasColumnName("decimal_value");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<long?>("IntegerValue")
                        .HasColumnType("bigint")
                        .HasColumnName("integer_value");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifier_id");

                    b.Property<Guid?>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid?>("RowId")
                        .HasColumnType("uuid")
                        .HasColumnName("row_id");

                    b.Property<int?>("RowOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("row_ordinal");

                    b.Property<string>("TextValue")
                        .HasColumnType("text")
                        .HasColumnName("text_value");

                    b.Property<string>("UnitCode")
                        .HasColumnType("text")
                        .HasColumnName("unit_code");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer")
                        .HasColumnName("value_type");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "RevisionId");

                    b.HasIndex("RevisionId", "DefinitionId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ux_journal_observation_null_row")
                        .HasFilter("row_id IS NULL");

                    b.HasIndex("RevisionId", "DefinitionId", "Role", "RowId")
                        .IsUnique()
                        .HasDatabaseName("ux_journal_observation_row")
                        .HasFilter("row_id IS NOT NULL");

                    b.ToTable("journal_experience_observations", null, t =>
                        {
                            t.HasCheckConstraint("ck_journal_observation_decimal", "decimal_value IS NULL OR (decimal_value BETWEEN -999999999999.999999 AND 999999999999.999999 AND decimal_value = round(decimal_value, 6))");

                            t.HasCheckConstraint("ck_journal_observation_ids", "definition_id <> '00000000-0000-0000-0000-000000000000'::uuid AND (row_id IS NULL OR row_id <> '00000000-0000-0000-0000-000000000000'::uuid) AND (option_id IS NULL OR option_id <> '00000000-0000-0000-0000-000000000000'::uuid)");

                            t.HasCheckConstraint("ck_journal_observation_limits", "(text_value IS NULL OR char_length(text_value) <= 2000) AND (unit_code IS NULL OR char_length(unit_code) <= 32)");

                            t.HasCheckConstraint("ck_journal_observation_row", "(row_id IS NULL AND row_ordinal IS NULL) OR (row_id IS NOT NULL AND row_ordinal IS NOT NULL AND row_ordinal BETWEEN 1 AND 12)");

                            t.HasCheckConstraint("ck_journal_observation_shape", "role IN (1,2) AND num_nonnulls(text_value, decimal_value, integer_value, boolean_value) = 1 AND ((value_type = 1 AND text_value IS NOT NULL) OR (value_type = 2 AND decimal_value IS NOT NULL) OR (value_type = 3 AND integer_value IS NOT NULL) OR (value_type = 4 AND boolean_value IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceUnknownReferenceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("OwnerLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_label");

                    b.Property<string>("ProducerLabel")
                        .HasColumnType("text")
                        .HasColumnName("producer_label");

                    b.HasKey("Id");

                    b.ToTable("journal_experience_unknown_references", null, t =>
                        {
                            t.HasCheckConstraint("ck_journal_unknown_label", "char_length(owner_label) BETWEEN 1 AND 256 AND char_length(btrim(owner_label)) > 0");

                            t.HasCheckConstraint("ck_journal_unknown_producer", "producer_label IS NULL OR char_length(producer_label) <= 256");
                        });
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ExternalIdentity.CustomerExternalIdentityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_user_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Provider", "Email");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("customer_external_identities", (string)null);
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ProductCollection.ProductCollectionItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSkuId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "ProductId")
                        .IsUnique();

                    b.HasIndex("CustomerId", "Status");

                    b.ToTable("product_collection_items", (string)null);
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ProductCollection.ProductExperienceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExperiencedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("PersonalText")
                        .HasMaxLength(7000)
                        .HasColumnType("character varying(7000)");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionItemId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("product_collection_experiences", (string)null);
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ProductCollection.ProductExperienceObservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<double?>("DecimalValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.Property<long?>("IntegerValue")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TextValue")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("UnitCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId", "DefinitionId", "Role")
                        .IsUnique();

                    b.ToTable("product_experience_observations", (string)null);
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ProductCollection.ProductExperienceTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId", "Value")
                        .IsUnique();

                    b.ToTable("product_experience_tags", (string)null);
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.StorefrontMembership.StorefrontMembershipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_account_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FirstAuthenticatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_authenticated_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<DateTime>("LastAuthenticatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_authenticated_at");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LegacyCustomerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("legacy_customer_profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<Guid>("StorefrontId")
                        .HasColumnType("uuid")
                        .HasColumnName("storefront_id");

                    b.HasKey("Id");

                    b.HasIndex("LegacyCustomerProfileId")
                        .IsUnique()
                        .HasDatabaseName("ux_storefront_memberships_legacy_profile")
                        .HasFilter("\"legacy_customer_profile_id\" IS NOT NULL");

                    b.HasIndex("StorefrontId")
                        .HasDatabaseName("ix_storefront_memberships_storefront");

                    b.HasIndex("CustomerAccountId", "StorefrontId")
                        .IsUnique()
                        .HasDatabaseName("ux_storefront_memberships_account_storefront");

                    b.ToTable("storefront_memberships", (string)null);
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.WishlistItem.WishlistItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSkuId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerId", "ProductId", "ProductSkuId")
                        .IsUnique();

                    b.ToTable("wishlist_items", (string)null);
                });

            modelBuilder.Entity("DKH.Platform.Authorization.ResourceAccess.Domain.ResourceTypeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("GrantCreatorFullAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsScopeOnly")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("ParentScopeTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("ResourceTypes");
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.CustomerAccount.LinkedCustomerIdentityEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.CustomerAccount.CustomerAccountEntity", null)
                        .WithMany("LinkedIdentities")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.CustomerAddress.CustomerAddressEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.CustomerProfile.CustomerProfileEntity", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.CustomerProfile.CustomerProfileEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.CustomerAccount.CustomerAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("DKH.CustomerService.Domain.ValueObjects.AccountStatus", "AccountStatus", b1 =>
                        {
                            b1.Property<Guid>("CustomerProfileEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BlockReason")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("block_reason");

                            b1.Property<DateTime?>("BlockedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("blocked_at");

                            b1.Property<string>("BlockedBy")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("blocked_by");

                            b1.Property<DateTime?>("LastActivityAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_activity_at");

                            b1.Property<DateTime?>("LastLoginAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_login_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasDefaultValue("Active")
                                .HasColumnName("account_status");

                            b1.Property<DateTime?>("SuspendedUntil")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("suspended_until");

                            b1.Property<int>("TotalOrdersCount")
                                .HasColumnType("integer")
                                .HasColumnName("total_orders_count");

                            b1.Property<decimal>("TotalSpent")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_spent");

                            b1.HasKey("CustomerProfileEntityId");

                            b1.ToTable("customer_profiles");

                            b1.WithOwner()
                                .HasForeignKey("CustomerProfileEntityId");
                        });

                    b.OwnsOne("DKH.CustomerService.Domain.ValueObjects.ContactVerification", "ContactVerification", b1 =>
                        {
                            b1.Property<Guid>("CustomerProfileEntityId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("EmailVerified")
                                .HasColumnType("boolean")
                                .HasColumnName("email_verified");

                            b1.Property<DateTime?>("EmailVerifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("email_verified_at");

                            b1.Property<bool>("PhoneVerified")
                                .HasColumnType("boolean")
                                .HasColumnName("phone_verified");

                            b1.Property<DateTime?>("PhoneVerifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("phone_verified_at");

                            b1.HasKey("CustomerProfileEntityId");

                            b1.ToTable("customer_profiles");

                            b1.WithOwner()
                                .HasForeignKey("CustomerProfileEntityId");
                        });

                    b.OwnsOne("DKH.CustomerService.Domain.ValueObjects.CustomerPreferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("CustomerProfileEntityId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("EmailNotificationsEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("email_notifications_enabled");

                            b1.Property<bool>("OrderStatusUpdates")
                                .HasColumnType("boolean")
                                .HasColumnName("order_status_updates");

                            b1.Property<string>("PreferredCurrency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("preferred_currency");

                            b1.Property<string>("PreferredLanguage")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("preferred_language");

                            b1.Property<bool>("PromotionalOffers")
                                .HasColumnType("boolean")
                                .HasColumnName("promotional_offers");

                            b1.Property<bool>("SmsNotificationsEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("sms_notifications_enabled");

                            b1.Property<bool>("TelegramNotificationsEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("telegram_notifications_enabled");

                            b1.HasKey("CustomerProfileEntityId");

                            b1.ToTable("customer_profiles");

                            b1.WithOwner()
                                .HasForeignKey("CustomerProfileEntityId");
                        });

                    b.Navigation("AccountStatus")
                        .IsRequired();

                    b.Navigation("ContactVerification")
                        .IsRequired();

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceEntryEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.CustomerAccount.CustomerAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceUnknownReferenceEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "UnknownReferenceId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceMutationReceiptEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.CustomerAccount.CustomerAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "EntryId", "ResultRevision")
                        .HasPrincipalKey("AccountId", "EntryId", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceRevisionEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.CustomerAccount.CustomerAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceProfileSnapshotEntity", null)
                        .WithMany()
                        .HasForeignKey("ProfileSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceEntryEntity", null)
                        .WithMany("Revisions")
                        .HasForeignKey("AccountId", "EntryId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceRevisionObservationEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.CustomerAccount.CustomerAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceRevisionEntity", null)
                        .WithMany("Observations")
                        .HasForeignKey("AccountId", "RevisionId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceUnknownReferenceEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.CustomerAccount.CustomerAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ExternalIdentity.CustomerExternalIdentityEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.CustomerProfile.CustomerProfileEntity", null)
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ProductCollection.ProductCollectionItemEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.CustomerProfile.CustomerProfileEntity", null)
                        .WithMany("ProductCollectionItems")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ProductCollection.ProductExperienceEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.ProductCollection.ProductCollectionItemEntity", "CollectionItem")
                        .WithOne("Experience")
                        .HasForeignKey("DKH.CustomerService.Domain.Entities.ProductCollection.ProductExperienceEntity", "CollectionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionItem");
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ProductCollection.ProductExperienceObservationEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.ProductCollection.ProductExperienceEntity", null)
                        .WithMany("Observations")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ProductCollection.ProductExperienceTagEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.ProductCollection.ProductExperienceEntity", null)
                        .WithMany("Tags")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.StorefrontMembership.StorefrontMembershipEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.CustomerAccount.CustomerAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DKH.CustomerService.Domain.Entities.CustomerProfile.CustomerProfileEntity", null)
                        .WithOne()
                        .HasForeignKey("DKH.CustomerService.Domain.Entities.StorefrontMembership.StorefrontMembershipEntity", "LegacyCustomerProfileId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.WishlistItem.WishlistItemEntity", b =>
                {
                    b.HasOne("DKH.CustomerService.Domain.Entities.CustomerProfile.CustomerProfileEntity", null)
                        .WithMany("WishlistItems")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.CustomerAccount.CustomerAccountEntity", b =>
                {
                    b.Navigation("LinkedIdentities");
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.CustomerProfile.CustomerProfileEntity", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ExternalIdentities");

                    b.Navigation("ProductCollectionItems");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceEntryEntity", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ExperienceJournal.ExperienceRevisionEntity", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ProductCollection.ProductCollectionItemEntity", b =>
                {
                    b.Navigation("Experience");
                });

            modelBuilder.Entity("DKH.CustomerService.Domain.Entities.ProductCollection.ProductExperienceEntity", b =>
                {
                    b.Navigation("Observations");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
